### PR TITLE
Uses inventory image from quay.io

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by jpramos123** [comment]
LGTM! inventory containers are up and running...

@sthirugn Let me know if I can approve the merge or if you wanna make it...

Thanks

**Comment by sthirugn** [comment]
is this for using quay inventory image versus building it ourselves? (since they moved from centos to python ubi8?)

**Comment by jpramos123** [comment]
@sthirugn Correct, this is to use quay.io, I believe README.md needs to be updates as well so we use

`docker login quay.io` instead `docker login https://registry.redhat.io`

**Comment by sthirugn** [comment]
@jpramos123 good point. I like for us to do a full run test before merging this.

I like to understand which images are being pulled from Red Hat registry and which are from quay.

**Comment by jpramos123** [comment]
@sthirugn Just tested again and this is working fine now...

**Review by sthirugn — APPROVED** [review]

**Pull request merged**
