### PR TITLE
Adds selinux flags to docker-compose config files

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by petrblaho** [comment]
Volume definition in docker-compose file doesn't allow `:z` flag in long format.

**Comment by petrblaho** [comment]
Also I did not try that on any other distro than Fedora, so I have no idea how that behaves on distros without Selinux.

**Comment by petrblaho** [comment]
https://issues.redhat.com/browse/DRFT-111

**Comment by sthirugn** [comment]
I think it was discussed last week that this was working fine. Merging now.

**Pull request merged**
